config/routes.rb
CareMatcher::Application.routes.draw do
  resources :users
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
 
  resources :conversations
  resources :messages do
    member do
      delete :trash
      post :untrash
    end
  end
  resources :care_givers
  resources :care_jobs
  resources :care_finders
  resources :contacts do 
    member do 
      post :decline
      post :accept
    end
  end

  resources :subscriptions

  get '/', to: 'users#show', constraints: lambda { |request| request.session[:user_id].present? }

  get '/', to: 'users#new'

  get '/care_finders/:id/jobs', to: 'care_finders#jobs', as: 'care_finder_jobs'

  

end

app/models/care_job.rb
class CareJob < ActiveRecord::Base
  include PublicActivity::Common
   
  belongs_to :care_finder
  has_many :contacts
  has_many :availabilities
  has_many :care_needs
  has_many :qualifications
  has_many :experiences
  has_many :interests
  has_many :hobbies
  has_many :pref_locations
  
  has_attached_file :photo, styles: { medium: "300x300", thumb: "100x100" }, default_url: "/images/CFA.jpg"

  def self.delete_care_job(id)
    CareJob.where(id: id).first.update_attributes(hidden: true)
  end

  include PgSearch
  pg_search_scope :search, against: [:name, :description]

  def self.text_search(query)
   if query.present?
     search(query)
   else
    scoped
   end
  end
end

app/controllers/care_jobs_controller.rb
class CareJobsController < ApplicationController

  before_filter :authorize, only: [:new, :destroy, :edit, :update]

  def index
    @carejobs = CareJob.where(hidden: false).text_search(params[:query])
  end

  def show
    @carejob = CareJob.where(id: params[:id]).first
  end

  def new
    @carejob = current_user.role.care_jobs.new
  end

  def create
    @carejob = current_user.role.care_jobs.new(care_job_params)
    @carejob.save
    @carejob.create_activity(:create, owner: current_user)
    redirect_to care_finder_jobs_path(current_user.role.id)
  end
  
  def destroy
    if CareJob.delete_care_job(params[:id])
      flash[:success] = "Care Job Deleted!"
      redirect_to care_finder_jobs_path(current_user.role.id)
    else
      render "index"
    end
  end

  def edit
    @carejob = CareJob.find(params[:id])
  end
  
  def update
    if CareJob.update(params[:id], care_job_params)
      flash[:success] = "Care Job Edited!"
      redirect_to care_finder_jobs_path(current_user.role.id)
    else
      render "edit"
    end
  end

private

  def care_job_params
    params.require(:care_job).permit(:name, :rate, :description, :photo)
  end


end

app/helpers/care_jobs_helper.rb
module CareJobsHelper
end

app/views/care_jobs/edit.html.slim
h1 edit care_job
= simple_form_for(@carejob, html: {class: 'form-horizontal'}) do |f|
    = f.input :name, input_html: {class: 'span-3'} 
    = f.input :rate
    = f.input :description, input_html: {class: 'span-6'} 
    = f.input :photo, as: :photo, input_html: {class: 'span-3'} 
    = f.button :submit, class: 'btn-primary'

app/views/care_jobs/index.html.slim
h1 = link_to "All CareJobs", care_jobs_path

= form_tag care_jobs_path, method: :get do
  = text_field_tag :query, params[:query]
  = submit_tag "Search"

- if @carejobs.blank? && params[:query].nil? && current_user.role_type == "CareFinder"
  p no jobs listed please add one.
  = link_to "Manage My Jobs", care_finder_jobs_path(current_user.role.id)
- elsif @carejobs.blank? && current_user.role_type == "CareFinder"
  p search found no entries please try again 
  = link_to "Manage My Jobs", care_finder_jobs_path(current_user.role.id)

- else  
  table
    tr 
      th Name
      th Description
      th Hourly Rate
      th
      th 

    - @carejobs.each do |job|
      tr
        td = job.name
        td = job.description
        td = job.rate
        td = link_to "View", care_job_path(job)
  = if current_user.role_type == "CareFinder"
    = link_to "Manage My Jobs", care_finder_jobs_path(current_user.role.id)
  

app/views/care_jobs/new.html.slim
h1 new care job
= simple_form_for(@carejob, html: {class: 'form-horizontal'}) do |f|
    = f.input :name, input_html: {class: 'span-3'} 
    = f.input :rate
    = f.input :description, input_html: {class: 'span-6'} 
    = f.button :submit, class: 'btn-primary'

app/views/care_jobs/show.html.slim
h1 show care jobs 

h2 Name
p = @carejob.name

h2 Description
p = @carejob.description

h2 Rate
p = @carejob.rate
- if current_user 
  = link_to "Request Contact", new_contact_path(care_job_id: params[:id])