config/routes.rb
CareMatcher::Application.routes.draw do
  resources :users
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
 
  resources :conversations
  resources :messages do
    member do
      delete :trash
      post :untrash
    end
  end
  resources :care_givers
  resources :care_jobs
  resources :care_finders
  resources :contacts do 
    member do 
      post :decline
      post :accept
    end
  end

  resources :subscriptions

  get '/', to: 'users#show', constraints: lambda { |request| request.session[:user_id].present? }

  get '/', to: 'users#new'

  get '/care_finders/:id/jobs', to: 'care_finders#jobs', as: 'care_finder_jobs'

  

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  require 'will_paginate/array' 
  before_filter :authorize
  before_filter :paid?
  before_filter :get_mailbox, :get_box, :get_actor
  before_filter :check_current_subject_in_conversation, :only => [:show, :update, :destroy]
  
  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox.paginate(page: params[:page], per_page: 9)
    else
      @conversations = @mailbox.trash.paginate(page: params[:page], per_page: 9)
    end 
    respond_to do |format|
      format.html { render @conversations if request.xhr? }
    end
  end

  def show
    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    render :action => :show
    @receipts.mark_as_read
  end

  def update
    if params[:untrash].present?
      @conversation.untrash(@actor)
    end

    if params[:reply_all].present?
      last_receipt = @mailbox.receipts_for(@conversation).last
      @receipt = @actor.reply_to_all(last_receipt, params[:body])
    end

    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    redirect_to :action => :show
    @receipts.mark_as_read

  end

  def destroy

    @conversation.move_to_trash(@actor)

    respond_to do |format|
      format.html {
        if params[:location].present? and params[:location] == 'conversation'
          redirect_to conversations_path(:box => :trash)
        else
          redirect_to conversations_path(:box   => @box,:page => params[:page])
        end
      }
      format.js {
        if params[:location].present? and params[:location] == 'conversation'
          render :js => "window.location = '#{conversations_path(:box => @box,:page => params[:page])}';"
        else
          render 'conversations/destroyroy'
        end
      }
    end
  end

  private

  def get_mailbox
    @mailbox = role_user.mailbox
  end

  def get_actor
    @actor = role_user
  end

  def get_box
    if params[:box].blank? or !["inbox", "trash"].include?params[:box]
      params[:box] = 'inbox'
    end

    @box = params[:box]
  end

  def check_current_subject_in_conversation
    @conversation = Conversation.find_by_id(params[:id])

    if @conversation.nil? or !@conversation.is_participant?(@actor)
      redirect_to conversations_path(:box => @box)
      return
    end
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.slim
h1 Conversations
=> link_to "Inbox", conversations_path
=> link_to "Trash", conversations_path(box: :trash)
- if @conversations.present?
  - @conversations.each do |conversation|
    h3
      | Subject:  
      => conversation.subject
      br
      - conversation.recipients.each do |recipient|
        = recipient.full_name
      => link_to "View", conversation_path(conversation.id)
      - if @box == 'trash'
        = link_to "Untrash", conversation_path(conversation, untrash: true), class: :button, method: :put
      - else
        = link_to "Trash", conversation, class: :button, method: :delete
  = will_paginate @conversations
- else 
  h3 No conversations exist 

app/views/conversations/show.html.slim
h1 = @conversation.subject
h1 
  => link_to "Inbox", conversation_path(params[:id])
  /=> link_to "Sentbox", conversation_path(box: :sentbox)
  => link_to "Trash", conversation_path(box: :trash)
ul
  = content_tag_for(:li, @receipts) do |receipt|
    h3= receipt.message.sender.full_name 
    p= receipt.message.body

    #actions
      - if receipt.is_trashed?
        = link_to "Untrash", untrash_message_path(receipt), class: :button, method: :post
      - else
        = link_to "Trash", trash_message_path(receipt), class: :button, method: :delete
= form_tag conversation_path(@conversation), :method => :put, :class => "cont_conversation"
  #editor
   = text_area_tag :body, nil,:rows =>6, :cols=> 53, :class => "required form_tag"
  #actions
    = submit_tag "Reply",  :name => :reply_all,:class => "btn"