config/routes.rb
CareMatcher::Application.routes.draw do
  resources :users
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
 
  resources :conversations
  resources :messages do
    member do
      delete :trash
      post :untrash
    end
  end
  resources :care_givers
  resources :care_jobs
  resources :care_finders
  resources :contacts do 
    member do 
      post :decline
      post :accept
    end
  end

  resources :subscriptions

  get '/', to: 'users#show', constraints: lambda { |request| request.session[:user_id].present? }

  get '/', to: 'users#new'

  get '/care_finders/:id/jobs', to: 'care_finders#jobs', as: 'care_finder_jobs'

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :care_giver
  belongs_to :care_job
  validates :care_job_id, presence: true
  
  acts_as_messageable
  state_machine :state, initial: :requested do

    event :decline do 
      transition requested: :declined,
                 accepted: :declined
    end

    event :accept do 
      transition requested: :accepted,
                 declined: :accepted
    end

  end


  def get_messages
    unless (conversation ||= self.mailbox.conversations.where(subject: "#{id}")).empty?
      conversation.first.receipts_for(self)
    end
  end

  def mailboxer_email(object)

  end

  def find_id(param_id)
    if param_id == "care_job_id"
      :care_job_id
    elsif param_id == "care_giver_id"
      :care_giver_id
    end
  end

  def to_name(role)
    if role[0] == "care_giver_id"
      caregiver_name(role[1])
    elsif role[0] == "care_job_id"
      carefinder_name(role[1])
    end
  end

  def from_name(role_type, role_id)
    if role_type == "CareGiver"
      caregiver_name(role_id)
    elsif role_type == "CareFinder"
      carefinder_name(role_id)
    end
  end

  def to_msg(role_type)
    if owner_role == role_type
      to_msg_as_owner
    else
      to_msg_not_as_owner
    end
  end

  def to_msg_as_owner
    if owner_role == "CareFinder"
      CareGiver.where(id: care_giver_id).first
    elsif owner_role == "CareGiver"
      self.care_job.care_finder
    end
  end

  def to_msg_not_as_owner
    if owner_role == "CareGiver"
      CareGiver.where(id: care_giver_id).first
    elsif owner_role == "CareFinder"
      self.care_job.care_finder
    end
  end

private
  def caregiver_name(role)
    name = CareGiver.where(id: role).first
    fullname(name)
  end

  def carefinder_name(role)
    name = CareJob.where(id: role).first.care_finder
    fullname(name)
  end

  def fullname(name)
    "#{name.first_name} #{name.last_name}"
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :is_owner?, only: :accept
  before_filter :authorize
  before_filter :paid?

  def new
    @contact = current_user.role.contacts.new
    @contact[:to] = @contact.to_name(params.first)
    @contact[@contact.find_id(params.first[0])] = params.first[1]
  end

  def create
    @contact = current_user.role.contacts.new(contact_params)
    @contact[:from] = @contact.from_name(current_user.role_type, current_user.role_id)
    @contact[:owner_role] = current_user.role_type

    if @contact.save
      flash[:success] = "Contact Request Sent!"
      redirect_to contacts_path
    else
      render "new"
      Rails.logger.info(@contact.errors.inspect) 
    end
  end

  def index
    @contacts = role_user.contacts.where.not(state: 'declined')
  end

  def decline
    @contact = role_user.contacts.where(id: params[:id]).first
    if @contact.decline
      role_user.reply_to_conversation(@contact.mailbox.conversations.first, params[:contact][:message])
      flash[:success] = "Contact Request Declined!"
      redirect_to contact_path
    else
      flash[:failure] = "Decline failed!"
      redirect_to contact_path
    end
  end

  def accept
    @contact = role_user.contacts.where(id: params[:id]).first
    if @contact.accept
      role_user.send_message(@contact.to_msg(current_user.role_type), params[:contact][:message], "Contact Accepted")
      flash[:success] = "Contact Request Accepted!"
      redirect_to contact_path
    else
      flash[:failure] = "Accept failed!"
      redirect_to contact_path
    end
  end
  
  def show
    @contact = Contact.where(id: params[:id]).first
    @owner = is_owner_view?
  end



private
  
  def contact_params
    params.require(:contact).permit(:to, :message, :care_job_id, :care_giver_id)
  end

  def is_owner?
    if name = role_user.contacts.where(id: params[:id]).first
      if name.owner_role == role_user.class.name
      flash[:error] = "Unauthorised Action"
      redirect_to contact_path(params[:id])
      end
    else
    end
  end

  def is_owner_view?
    if name = role_user.contacts.where(id: params[:id]).first
      if name.owner_role == role_user.class.name
        true
      end
    else
      false
    end
  end




end

app/views/contacts/index.html.slim
h1 Contact Requests

table
  tr 
    th Created at
    th To
    th State
    th

  - @contacts.each do |contact|
    tr
      td = contact.created_at
      td = contact.to
      td = contact.state
      td = link_to "View", contact_path(contact)
      td = link_to "Decline", decline_contact_path(contact)

app/views/contacts/new.html.slim
h1 New Contact Request
p to: #{@contact.to}
= simple_form_for(@contact, html: {class: 'form-horizontal'}) do |f|
  = f.input :to, as: :hidden, value: "#{@contact.to}"
  - if current_user.role_type == "CareFinder"
    = f.input :care_job_id, collection: role_user.care_jobs, prompt: "Please select", label: "For"
    = f.input :care_giver_id, as: :hidden, value: @contact.care_giver_id
  - elsif current_user.role_type == "CareGiver"
    = f.input :care_job_id, as: :hidden, value: @contact.care_job_id

  = f.input :message, input_html: {class: 'span-3', value: "Hi #{@contact.to}, I would like to request contact with you."}
  = f.button :submit, class: 'btn-primary'

app/views/contacts/show.html.slim
h1 Contact Request

h3
  | Requested by: 
  = @contact.from

h3 
  | To: 
  = @contact.to

h3
  | State: 
  = @contact.state
= simple_form_for(@contact, html: {class: 'form-horizontal'}, method: :post) do |f|
  = f.input :message
  - unless @owner
    = f.button :submit, value: "Accept", action: "accept"
  = f.button :submit, value: "Decline", action: "decline", confirm: "Are you sure?", confirm: "Are you sure?"

br
p ----------------------------------
- if receipts ||= @contact.get_messages
  - receipts.each do |receipt|
    h3 = receipt.message.sender.full_name
    p = receipt.message.body